name: e_commerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter_native_splash: ^2.4.1
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  iconsax: ^0.0.8

  # Icons
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


  # Utilities Packages

  http: ^1.2.2
  intl: ^0.19.0
  logger: ^2.4.0
  url_launcher: ^6.3.0
  smooth_page_indicator: ^1.2.0+3


  
  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

flutter:
  uses-material-design: true


  assets:
    - assets/icons/brands/
    - assets/icons/categories/
    - assets/icons/payment_methods/
    - assets/fonts/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/content/
    - assets/images/reviews/
    - assets/images/products/
    - assets/logos/

  fonts:
    - family: poppins
      fonts:
      - asset: assets\fonts\Poppins-Bold.ttf
        weight: 800
      - asset: assets\fonts\Poppins-italic.ttf
        style: italic
      - asset: assets\fonts\Poppins-Light.ttf
        weight: 300
      - asset: assets\fonts\Poppins-Medium.ttf
        weight: 500
      - asset: assets\fonts\Poppins-MediumItalic.ttf
        style: italic
        weight: 500
      - asset: assets\fonts\Poppins-Regular.ttf
        weight: 400
      - asset: assets\fonts\Poppins-SemiBold.ttf
        weight: 600

# flutter_native_splash:
#   android: true
#   ios: true
#   web: true
#   color: "#FFFFFF"
#   color_dark: "#272727"
#   image: "assets/logos/t-store-splash-logo-black.png"
#   image_dark: assets/logos/t-store-splash-logo-white.png
#   android_12:
#   color : "#FFFFFF"
#   color_dark: "#272727"
#   image: assets/logos/t-store-splash-logo-black.png
#   image_dark: assets/logos/t-store-splash-logo-white.png

